### ISSUE TITLE
Inbound breaking change in Wasmtime 0.28.0 NuGet package

### ISSUE THREAD

**Issue by peterhuene** [deislabs/wagi-dotnet#23]
Hey all,

I wanted to file an issue to inform you of breaking changes that are coming in 0.28.0 of the Wasmtime package.

The Wasmtime Rust API underwent a major refactoring in 0.28.0 to make it safer to use in multithreaded async executors. This has breaking changes for the .NET API as well.

As part of updating the .NET API to use the new Wasmtime API, I decided to make some changes to better make the .NET API match the other language bindings.

The biggest change is that `Host` no longer exists in the .NET API.  This type has been replaced with the `Linker` type that functions much like the Rust version does; you use it to define imports to module instantiations.

Another big change is that `Instance` no longer implements `DynamicObject` for invoking methods or interacting with globals.  You'll want to use `Instance.GetFunction` to get the function exported by the instance and then use `Function.Invoke` to call it.

One thing I did notice while just looking at the WAGI implementation is that the `Engine` and `Module` are both created per request; `Module` should be kept as long-lived as possible as it does the actual JIT compilation when created (and by default in the non-Rust language bindings, the JIT result is not cached).

If you have any questions about how to migrate to 0.28.0 when it is released (ETA tomorrow), I'm happy to help, just @ me on GitHub.

**Comment by simongdavies** [comment]
@peterhuene  Thanks for the heads-up , I saw your tweet about this. I will take a look at this and let you know if I have any issues or questions. On the lifetimes of the Engine/Host I observed that the first execution always took measurably longer so it appeared that the compellation was being cached but it must have been some other effect, I'll take a look at this as well.

**Comment by peterhuene** [comment]
Under the covers the .NET API calls `wasm_engine_new` or `wasm_config_new`, both of which end up calling `Config::default()` on the Rust side; that returns a config with an empty cache configuration, so code caching shouldn't be occurring.  The 0.28.0 version of the .NET API should allow enabling cache configuration.

I can't explain why you'd be seeing a significant speed up on subsequent creations of `Module`, but even with pulling the module from the code cache and thereby skipping the JIT, reading the module from the cache is still a significant cost compared to instantiation (it may even be a multiple orders of magnitude difference, i.e. `ms` vs. `us`).

If possible, creating a particular `Module` should happen once and can then be instantiated any number of times.

**Comment by peterhuene** [comment]
FYI, we've released [0.28.0](https://github.com/bytecodealliance/wasmtime-dotnet/releases/tag/v0.28.0) of the Wasmtime package.

**Comment by simongdavies** [comment]
Thanks, I will look at fixing the per-request creation of engine and modules when I move to 0.28.0.
