### ISSUE TITLE
bug: cannot run the binary directly; configuration files not found

### ISSUE THREAD

**Issue by squillace** [deislabs/wagi-dotnet#8]
repro: 

- `dotnet new -i Deislabs.WAGI.Templates::0.1.0-preview`
- `dotnet new wagi -n hatred`
- `dotnet build -c Release`
- `/hatred/bin/Release/net5.0/hatred`

expected result: should run

obtained result:

```
fail: Deislabs.WAGI.Extensions[0]
      No configuration found in section WASM
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/squillace/work/squillace/blowschunk/hatred
```

**Comment by simongdavies** [comment]
This is caused by not setting the  ASPNETCORE_ENVIRONMENT environment variable. To fix this run ```export  ASPNETCORE_ENVIRONMENT="Development"``` prior to running the application. Docs are updated to reflect this.

**Comment by squillace** [comment]
but what if I want to run it as "Release"? is that the setting to use in that case?

**Comment by simongdavies** [comment]
If you want to run with the default environment setting (Production) then you should rename the file /home/squillace/work/squillace/blowschunk/hatred/appsettings.Development.json to /home/squillace/work/squillace/blowschunk/hatred/appsettings.Production.json, then there would be no need to set the environment variable. 

I'll add a fix to the template to copy the modules files to the output directory on build and publish as running the app at present only works if you run from the project directory.

**Comment by squillace** [comment]
so, lemme understand. IFF I want to run directly but as dev env I must set the Env var to "Development"; but if I wish to do the same, I have to copy in a appsettings.Production.json file and then I do NOT need to set any env var?

Who thought that made any sense? In any case, let's nail all these operations down precisely, as it'll serve as the working model going forward for any other wasm/wasi.net templates we do, yes?

**Comment by simongdavies** [comment]
Its really to do with the defaults ASP.Net core uses and the choices I made when I buillt the template project, by default ASP.Net will load a settings file called appSettings.<Environment>.json , and by default if no environment setting is provided then the environment defaults to Production. Alongside this I chose to place the WASM configuration in a file called appSettings.Development.json in the template, this means either the environment needs to be set or the configuration needs to be moved. One way to avoid all this would be to place the WASM configuration in appSettings.json file in the template and then it will just work.

**Comment by squillace** [comment]
all right, that makes sense. When we get to the end, let's do the thing that makes complete sense for dev iteration using this environment, _and then tackle the larger question of how the model should work across app templates_ per our discussion yesterday....

**Comment by simongdavies** [comment]
updated the template so that build/publish work without further configuration
